language: node_js
node_js:
  - '8'
  - '10'
  - '12'
before_install: 'sudo apt-get update && sudo apt-get install -y libjpeg-progs'
script: 'npm run ci'
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'
